// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-CpVLxWsf_53Hga1YJ2HDXjWfr7U8OE',
    appId: '1:143774411675:web:8e2ef356af0343d6d9cf3e',
    messagingSenderId: '143774411675',
    projectId: 'smart-kuweta',
    authDomain: 'smart-kuweta.firebaseapp.com',
    storageBucket: 'smart-kuweta.firebasestorage.app',
    measurementId: 'G-FENFR2GTK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUE_ZxkVKiYg2RDpTBydV_XLCmGhdigAE',
    appId: '1:143774411675:android:4753938f2b77d2fad9cf3e',
    messagingSenderId: '143774411675',
    projectId: 'smart-kuweta',
    storageBucket: 'smart-kuweta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKE3PDpluwQhp7dWFDmsxE6ZKX9wcoCk',
    appId: '1:143774411675:ios:ab6e01f6b132adb9d9cf3e',
    messagingSenderId: '143774411675',
    projectId: 'smart-kuweta',
    storageBucket: 'smart-kuweta.firebasestorage.app',
    iosBundleId: 'com.example.smartKuweta',
  );
}
